
spring:
  application:
    name: job-service
  flyway:
    schemas: default
    locations: classpath:db/migration/default

multitenancy:
  tenants:
    - identifier: google
      enabled: true
      schema: google
    - identifier: meta
      enabled: true
      schema: meta
    - identifier: apple
      enabled: false
      schema: apple